name: 🚀 Deploy React App to EC2

on:
  push:
    branches:
      - main   # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24.x

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🏗 Build React App
        run: npm run build

      - name: 🔐 Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: 📤 Upload Build to EC2
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no -r build/* ubuntu@15.206.65.30:/home/ubuntu/build/

      - name: 🚀 Deploy on Server
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@15.206.65.30 << 'EOF'

            echo "🧹 Cleaning old files..."
            sudo rm -rf /var/www/html/*

            echo "📂 Copying new build..."
            sudo cp -r /home/ubuntu/build/* /var/www/html/

            echo "🔄 Reloading Nginx..."
            sudo systemctl reload nginx

            echo "✅ Deployment Done"

          EOF

      - name: 🌐 Health Check
        run: curl -I https://sarasgurukul.com