name: 🚀 Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24.7.0

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🏗 Build React App
        run: CI=false npm run build

      - name: 🔐 Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: 📤 Upload Build
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no -r build/* ubuntu@15.206.65.30:/home/ubuntu/build/

      - name: 🚀 Deploy
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@15.206.65.30 << 'EOF'
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/build/* /var/www/html/
            sudo systemctl reload nginx
          EOF

      - name: 🌐 Health Check
        run: curl -I https://sarasgurukul.com